### ISSUE TITLE
Missing bundle.js mentioned in index.html

### ISSUE THREAD

**Issue by apanasara** [loonywizard/native-js-dnd-list#3]
Example shows **bundle.js**. But not found in your library.

Kindly *provide documentation* for further usage of this library.

![image](https://user-images.githubusercontent.com/902578/70428588-d17be700-1a9c-11ea-9210-9dad089d8109.png)

**Comment by loonywizard** [comment]
Hi! `/dist` folder is in [.gitignore](https://github.com/loonywizard/native-js-dnd-list/blob/master/.gitignore). It is a good practice to exclude folders like dist or node_modules from git repository
